<?php

$title = 'Registration';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$login = $form->get('username');
$login->setAttribute('class', 'form-control');
$login->setAttribute('placeholder', 'enter username');

$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'enter password');

$confirmpassword = $form->get('confirmpassword');
$confirmpassword->setAttribute('class', 'form-control');
$confirmpassword->setAttribute('placeholder', 'confirm password');

$mail = $form->get('email');
$mail->setAttribute('class', 'form-control');
$mail->setAttribute('placeholder', 'enter email');

$tel = $form->get('telephone');
$tel->setAttribute('class', 'form-control');
$tel->setAttribute('placeholder', 'enter contact telephone');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', ['action' => 'registration']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($login) ?>
    <?= $this->formElement($login) ?>
    <?= $this->formElementErrors()->render($login, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($confirmpassword) ?>
    <?= $this->formElement($confirmpassword) ?>
    <?= $this->formElementErrors()->render($confirmpassword, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($mail) ?>
    <?= $this->formElement($mail) ?>
    <?= $this->formElementErrors()->render($mail, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($tel) ?>
    <?= $this->formElement($tel) ?>
    <?= $this->formElementErrors()->render($tel, ['class' => 'help-block']) ?>
</div>

<?php

echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>

<a style="margin-top: 20px" class="btn btn-primary" href="<?= $this->url('user', ['action' => 'login']) ?>">Login</a>