<?php
$title = 'Items';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<table class="table">
<tr>
    <th>Items name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Created</th>
    <th>Order</th>
</tr>
<?php foreach ($paginator as $item) : ?>
    <tr>
        <td><?= $this->escapeHtml($item->name) ?></td>
        <td><?= $this->escapeHtml($item->description) ?></td>
        <td><?= $this->escapeHtml($item->price) ?></td>
        <td><?= $this->escapeHtml($item->quantity) ?></td>
        <td><?= $this->escapeHtml($item->created) ?></td>
        <td>
            <a href="<?= $this->url('order', ['action' => 'add', 'id' => $item->id]) ?>">Order</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'items']
) ?>