<?php
$title = 'Items';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<table class="table">
<tr>
    <th>Items name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Created</th>
    <th>Order</th>
</tr>
<?php foreach ($items as $item) : ?>
    <tr>
        <td><?= $this->escapeHtml($item->name) ?></td>
        <td><?= $this->escapeHtml($item->description) ?></td>
        <td><?= $this->escapeHtml($item->price) ?></td>
        <td><?= $this->escapeHtml($item->quantity) ?></td>
        <td><?= $this->escapeHtml($item->created) ?></td>
        <td>
            <a href="<?= $this->url('cart', ['action' => 'add', 'id' => $item->id]) ?>">Order</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>