<?php
$title = 'itemsList';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<table class="table">
<tr>
    <th>Items name</th>
    <th>Description</th>
    <th>price</th>
    <th>quantity</th>
    <th>created</th>
    <th>update</th>
    <th>delete</th>
</tr>
<?php foreach ($items as $item) : ?>
    <tr>
        <td><?= $this->escapeHtml($item->name) ?></td>
        <td><?= $this->escapeHtml($item->description) ?></td>
        <td><?= $this->escapeHtml($item->price) ?></td>
        <td><?= $this->escapeHtml($item->quantity) ?></td>
        <td><?= $this->escapeHtml($item->created) ?></td>
         <td>
            <a href="<?= $this->url('items', ['action' => 'update', 'id' => $item->id]) ?>">Update</a>
        </td>
         <td>
            <a href="<?= $this->url('items', ['action' => 'delete', 'id' => $item->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<a href="<?= $this->url('items', ['action' => 'create']) ?>">Create Item</a>